version: '3.5'

services:
  rabbit1:
    build: 
      context: ./rabbitmq
      dockerfile: Dockerfile
    hostname: "rabbit1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
      - "61613:61613"
    labels:
      NAME: "rabbitmq1"
    volumes:
      - "./rabbitmq/data/log:/data/log"
      - "./rabbitmq/data/mnesia:/data/mnesia"

  postgres:
    image: postgres
    network_mode: bridge
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testdb
    volumes:
      - ./postgres:/data/postgres
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    expose: 
      - 5432
    ports:
      - 5432:5432
    restart: unless-stopped

  chatboot:
    image: "chatboot:1.0"
    build: 
      context: ../
      dockerfile: Dockerfile
    network_mode: bridge
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done;'
    hostname: chatboot
    expose:
      - 8080
    ports: 
      - 8080:8080
    depends_on:
      - rabbit1
      - postgres
    links:
      - postgres

volumes:
  postgres: